const allMineralNames = [
    "copper",
    "iron",
    "gold",
    "diamond",
    "uranium",
    "plutonium",
    "unobtanium",
    "crazium",
    "titanium",
    "silicon",
    "lithium",
    "carbon",
    "sodium",
    "potassium",
    "calcium",
    "tungsten",
    "nickel",
    "zinc",
    "lead",
    "aluminium",
    "mercury",
    "bismuth",
    "arsenic",
    "antimony",
    "tellurium",
    "selenium",
    "cadmium",
    "beryllium",
    "rhodium",
    "iridium",
    "osmium",
    "ruthenium",
    "palladium",
] as const;
type Mineral = (typeof allMineralNames)[number];
